apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: currency-converter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DISPLAY
          value: "host.docker.internal:0"
        # Note: GUI forwarding setup is required on the host for this to work
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
