apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: chirag075/convertechz:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DISPLAY
          value: "host.docker.internal:0"
        volumeMounts:
        - name: x11-unix
          mountPath: /tmp/.X11-unix
        # Note: GUI forwarding setup is required on the host for this to work
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: x11-unix
        hostPath:
          path: /tmp/.X11-unix
          type: Directory
